stages:
  - check
  - build

check:
  image: golangci/golangci-lint:v1.15
  stage: check
  script:
    - make check

build:
  image: golang:1.14
  stage: build
  script:
    - make build
  artifacts:
    untracked: true
    paths:
      - bin/
